#!/usr/bin/env python

"""

Output year histogram for movies in IMDB, for use when creating a graph.

"""

import argparse
import json

def load(h, l, path, verbose=False):
    with open(path, 'rt') as input:
    	 j = json.load(input)

	 for imdburl in j.keys():
             if imdburl in l:
                 continue
	     if 0 > imdburl.find("imdb.com"):
	         continue
             if 'free' != j[imdburl]['status']:
                 continue
             if 'year' not in j[imdburl]:
                 year = 'n/a'
             else:
                 year = int(j[imdburl]['year'])
             if not year in h:
                     h[year] = 0
             if verbose:
                 print imdburl, j[imdburl]['title']
             h[year] = h[year] + 1
             l[imdburl] = j[imdburl]

parser = argparse.ArgumentParser()
parser.add_argument('files', metavar='N', type=str, nargs='*',
                    default=['free-movies-manual.json'],
                    help='input file(s)')
parser.add_argument('--total', action='store_true', default=False)
args = parser.parse_args()

h = {}
l = {}
for file in args.files:
    load(h, l, file)

for y in sorted(h.keys()):
    print y, h[y]

if args.total:
    print "Total:", len(l.keys())
