#!/usr/bin/env python

"""
Extract list of free movies available from vodo.net.
"""

import json
import lxml.html
import movielib
import urllib2
import urlparse

def parsepage(l, url):
    try:
        html = movielib.http_get_read(url)
        root = lxml.html.fromstring(html)
        imdburl = url
        for a in root.cssselect("a"):
            if -1 != a.attrib['href'].find("imdb.com/title/"):
                imdburl = urlparse.urljoin(url, a.attrib['href'])
                if '/' != imdburl[-1]:
                    imdburl = imdburl + '/'
        if imdburl == url:
            print "warning: missing imdb link for %s" % url
        title = root.cssselect('meta[property="og:title"]')[0].get('content')
        year = root.cssselect('div.title-holder span.alt')[0].text_content().strip('()')
        l[imdburl] = {
            'status' : 'free',
            'freenessurl' : url,
            'title' : title,
            }
        if '' != year:
            l[imdburl]['year'] = int(year)

        #print(l[imdburl])
    except urllib2.HTTPError as e:
        pass
    return None

def main():
    url = "http://vodo.net/films/"
    html = movielib.http_get_read(url)
    root = lxml.html.fromstring(html)
    entries = {}
    for a in root.cssselect("div.sticker a"):
        entryurl = urlparse.urljoin(url, a.attrib['href'])
        parsepage(entries, entryurl)
    movielib.savelist(entries, 'free-movies-vodo.json')

if __name__ == '__main__':
    main()
