#!/usr/bin/env python

"""
Extract list of icheckmovies claimed IMDB entries on the Internet Archive.
"""

import json
import lxml.html
import movielib
import urllib2
import urlparse

def fetch(entries, urlbase):
    count = 0
    url = urlbase
    html = movielib.http_get_read(url)
    root = lxml.html.fromstring(html)
    for tr in root.cssselect("li.movie"):
        t = tr.cssselect("h2 a")
        if t:
            title = t[0].text_content().strip()
	    ta = tr.cssselect("a.optionIMDB")[0]
            imdburl = urlparse.urljoin(url, ta.attrib['href'])
            y = tr.cssselect("a.tagNamespaceYear")
            year = y[0].text_content()
            print imdburl, year, title
            entries[imdburl] = {
                'status' : 'free',
                'freenessurl' : url,
                'title' : title,
                }
            if '' != year:
                entries[imdburl]['year'] = int(year)
            count = count + 1
    return count

entries = {}
fetch(entries, "https://www.icheckmovies.com/lists/internet+archive/mochard/")
movielib.savelist(entries, 'free-movies-icheckmovies-archive-mochard.json')
